PROYECTO-FINANZAS/PROYECTO-FINANZAS.Web/Models/Deposito.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_FINANZAS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposito
    {
        public int DepositoId { get; set; }
        public decimal MontoDepositado { get; set; }
        public int NroDiasPlazoFijo { get; set; }
        public System.DateTime FechaDeposito { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public decimal Penalizacion { get; set; }
        public int CuentaCorrienteId { get; set; }
        public decimal TasaEfectiva { get; set; }
    
        public virtual CuentaCorriente CuentaCorriente { get; set; }
    }
}

PROYECTO-FINANZAS/PROYECTO-FINANZAS.Web/Controllers/CuentaCorrienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using PROYECTO_FINANZAS.Web.Filters;
using PROYECTO_FINANZAS.Web.Helpers;
using PROYECTO_FINANZAS.Web.ViewModel.CuentaCorriente;
using System.Transactions;

namespace PROYECTO_FINANZAS.Web.Controllers
{
    public class CuentaCorrienteController : BaseController
    {
        [RolAuthFilter()]
        public ActionResult ListarCuentas()
        {
            ListarCuentasViewModel ViewModel = new ListarCuentasViewModel();
            ViewModel.CargarDatos(Session.GetPerfilId());
            return View(ViewModel);
        }

        [RolAuthFilter()]
        public ActionResult Delete(int? CuentaId)
        {
            try
            {
                using (var tc = new TransactionScope())
                {
                    if (CuentaId.HasValue)
                    {
                        Models.CuentaCorriente ObjCuenta = Context.CuentaCorriente.FirstOrDefault(X => X.CuentaCorrienteId == CuentaId);
                        Context.Deposito.RemoveRange(ObjCuenta.Deposito);
                        Context.CuentaCorriente.Remove(ObjCuenta);
                        Context.SaveChanges();
                        TempData["Mensaje"] = "La cuenta corriente fue eliminada exitosamente";
                        tc.Complete();
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["Mensaje"] = "Error al eliminar la cuenta corriente, vuelva a intentarlo.";
            }
            return RedirectToAction("ListarCuentas");
        }

        [RolAuthFilter()]
        public ActionResult Edit(int? CuentaId)
        {
            CuentaViewModel ViewModel = new CuentaViewModel();
            ViewModel.CargarDatos(CuentaId);
            return View(ViewModel);
        }

        [HttpPost]
        public ActionResult Edit(CuentaViewModel ViewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ViewModel.CargarDatos(ViewModel.CuentaId);
                    TryUpdateModel(ViewModel);

                    TempData["Mensaje"] = "Por favor, complete los campos requeridos";
                    return View(ViewModel);
                }

                using (var tc = new TransactionScope())
                {
                    Models.CuentaCorriente ObjCuenta = null;

                    if (ViewModel.CuentaId.HasValue)
                        ObjCuenta = Context.CuentaCorriente.FirstOrDefault(X => X.CuentaCorrienteId == ViewModel.CuentaId);
                    else
                    {
                        ObjCuenta = new Models.CuentaCorriente();
                        ObjCuenta.PerfilId = Session.GetPerfilId();
                        Context.CuentaCorriente.Add(ObjCuenta);
                    }

                    ObjCuenta.NroCuenta = ViewModel.NroCuenta;
                    ObjCuenta.Banco = ViewModel.Banco;

                    Context.SaveChanges();
                    TempData["Mensaje"] = "La cuenta corriente fue procesada exitosamente";
                    tc.Complete();
                }
            }
            catch (Exception ex)
            {
                ViewModel.CargarDatos(ViewModel.CuentaId);
                TryUpdateModel(ViewModel);

                TempData["Mensaje"] = "Por favor, complete los campos requeridos";
                return View(ViewModel);
            }
            return RedirectToAction("ListarCuentas");
        }
    }
}

PROYECTO-FINANZAS/PROYECTO-FINANZAS.Web/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using PROYECTO_FINANZAS.Web.Filters;
using PROYECTO_FINANZAS.Web.Helpers;
using PROYECTO_FINANZAS.Web.ViewModel.Dashboard;

namespace PROYECTO_FINANZAS.Web.Controllers
{
    public class DashboardController : BaseController
    {
        [RolAuthFilter()]
        public ActionResult Index()
        {
            DashboardViewModel viewModel = new DashboardViewModel();
            viewModel.CargarDatos(Session.GetUsuarioId(), Session.GetPerfilId());
            return View(viewModel);
        }
    }
}

PROYECTO-FINANZAS/PROYECTO-FINANZAS.Web/Controllers/DepositoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using PROYECTO_FINANZAS.Web.Filters;
using PROYECTO_FINANZAS.Web.ViewModel.Deposito;
using System.Transactions;

namespace PROYECTO_FINANZAS.Web.Controllers
{
    public class DepositoController : BaseController
    {
        [RolAuthFilter()]
        public ActionResult ListarDepositos(int CuentaId)
        {
            ListarDepositosViewModel ViewModel = new ListarDepositosViewModel();
            ViewModel.CargarDatos(CuentaId);
            return View(ViewModel);
        }

        [RolAuthFilter()]
        public ActionResult Eliminar(int? DepositoId)
        {
            int AuxCuentaId = 0;
            try
            {
                using (var tc = new TransactionScope())
                {
                    if (DepositoId.HasValue)
                    {
                        Models.Deposito ObjDeposito = Context.Deposito.FirstOrDefault(X => X.DepositoId == DepositoId);
                        AuxCuentaId = ObjDeposito.CuentaCorrienteId;
                        Context.Deposito.Remove(ObjDeposito);
                        Context.SaveChanges();
                        TempData["Mensaje"] = "El deposito fue eliminado exitosamente";
                        tc.Complete();
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["Mensaje"] = "Error al eliminar el deposito, vuelva a intentarlo.";
            }
            return RedirectToAction("ListarDepositos", new { CuentaId = AuxCuentaId });
        }

        [RolAuthFilter()]
        public ActionResult Edit(int CuentaId, int? DepositoId)
        {
            DepositoViewModel ViewModel = new DepositoViewModel();
            ViewModel.CargarDatos(CuentaId, DepositoId);
            return View(ViewModel);
        }

        [HttpPost]
        public ActionResult Edit(DepositoViewModel ViewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ViewModel.CargarDatos(ViewModel.CuentaId, ViewModel.DepositoId);
                    TryUpdateModel(ViewModel);

                    TempData["Mensaje"] = "Por favor, complete los campos requeridos";
                    return View(ViewModel);
                }

                using (var tc = new TransactionScope())
                {
                    Models.Deposito ObjDeposito = null;

                    if (ViewModel.DepositoId.HasValue)
                        ObjDeposito = Context.Deposito.FirstOrDefault(X => X.DepositoId == ViewModel.DepositoId);
                    else
                    {
                        ObjDeposito = new Models.Deposito();
                        ObjDeposito.CuentaCorrienteId = ViewModel.CuentaId;
                        Context.Deposito.Add(ObjDeposito);
                    }

                    if(ViewModel.Tasa == "TNA")
                    {
                        Double Aux = 1 + (Double)ViewModel.ValorTasa / 360.0;
                        ObjDeposito.TasaEfectiva = (decimal)(Math.Pow(Aux, 360.0) - 1.0);
                    }
                    else if (ViewModel.Tasa == "TEA")
                    {
                        ObjDeposito.TasaEfectiva = ViewModel.ValorTasa;
                    }

                    ObjDeposito.Penalizacion = ViewModel.Penalizacion;
                    ObjDeposito.FechaDeposito = ViewModel.FechaDeposito;
                    ObjDeposito.MontoDepositado = ViewModel.MontoDepositado;
                    ObjDeposito.NroDiasPlazoFijo = ViewModel.NroDiasPlazoFijo;
                    ObjDeposito.FechaVencimiento = ViewModel.FechaDeposito.AddDays(ViewModel.NroDiasPlazoFijo);

                    Context.SaveChanges();
                    TempData["Mensaje"] = "El Deposito fue procesado exitosamente";
                    tc.Complete();
                }
            }
            catch (Exception ex)
            {
                ViewModel.CargarDatos(ViewModel.CuentaId, ViewModel.DepositoId);
                TryUpdateModel(ViewModel);

                TempData["Mensaje"] = "Por favor, complete los campos requeridos";
                return View(ViewModel);
            }
            return RedirectToAction("ListarDepositos", new { CuentaId = ViewModel.CuentaId});
        }
    }
}

PROYECTO-FINANZAS/PROYECTO-FINANZAS.Web/Views/Deposito/Edit.cshtml
@model PROYECTO_FINANZAS.Web.ViewModel.Deposito.DepositoViewModel

@{
    ViewBag.Title = "Administrar Deposito";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Administrar Deposito
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i>  <a href="@Url.Action("Index", "Dashboard")">Dashboard</a>
            </li>
            <li>
                <i class="fa fa-bank"></i>  <a href="@Url.Action("ListarDepositos", "Deposito", new { CuentaId = Model.CuentaId })">Mis Depositos</a>
            </li>
            <li class="active">
                <i class="fa fa-edit"></i> Administrar Deposito
            </li>
        </ol>
    </div>
</div>

@if (TempData["Mensaje"] != null)
{
    String Mensaje = TempData["Mensaje"].ToString();

    if (Mensaje.Contains("exitosamente"))
    {
        <div class="alert alert-success fade in" id="mensaje">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>@Mensaje
        </div>
    }
    else
    {
        <div class="alert alert-danger" id="mensaje">
            @Mensaje
        </div>
    }
}

<div class="panel panel-default">
    <div class="panel-heading text main-text">
        Administrar Deposito
    </div>
    <div class="panel-body">
        @using (Html.BeginForm("Edit", "Deposito", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @Html.HiddenFor(X => X.DepositoId)
            @Html.HiddenFor(X => X.CuentaId)

            <div class="form-group">
                <label>Fecha de Depósito</label>
                <input id="FechaDeposito" name="FechaDeposito" value="@Model.FechaDeposito.Date.ToShortDateString()" class="form-control" />
                @Html.ValidationMessageFor(X => X.FechaDeposito, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label>Número de Días del Plazo Fijo</label>
                @Html.TextBoxFor(X => X.NroDiasPlazoFijo, new { @class = "form-control" })
                @Html.ValidationMessageFor(X => X.NroDiasPlazoFijo, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label>Valor de la Tasa (%)</label>
                @Html.TextBoxFor(X => X.ValorTasa, new { @class = "form-control" })
                @Html.ValidationMessageFor(X => X.ValorTasa, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label>Tipo de Tasa</label>
                @Html.DropDownListFor(X => X.Tasa, new SelectList(Model.DicTasas, "Key", "Value"), "[-Seleccione-]", new { @class = "form-control" })
                @Html.ValidationMessageFor(X => X.Tasa, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label>Monto Depositado</label>
                @Html.TextBoxFor(X => X.MontoDepositado, new { @class = "form-control" })
                @Html.ValidationMessageFor(X => X.MontoDepositado, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label>Penalización (%)</label>
                @Html.TextBoxFor(X => X.Penalizacion, new { @class = "form-control" })
                @Html.ValidationMessageFor(X => X.Penalizacion, "", new { @class = "text-danger" })
            </div>
            <button type="submit" class="btn btn-danger square-btn-adjust"><i class="fa fa-save"></i> Guardar</button>
            <a href="@Url.Action("ListarDepositos", "Deposito", new { CuentaId = Model.CuentaId })" class="btn btn-danger square-btn-adjust"><i class="fa fa-arrow-left"></i> Cancelar</a>
        }
    </div>
</div>

<script src="@Url.Content("~/Content/js/jquery-1.10.2.js")"></script>

<script>
    $(function () {
        $("#FechaDeposito").datepicker();
    });
</script>

PROYECTO-FINANZAS/PROYECTO-FINANZAS.Web/Views/Deposito/ListarDepositos.cshtml
@model PROYECTO_FINANZAS.Web.ViewModel.Deposito.ListarDepositosViewModel

@{
    ViewBag.Title = "Mis Depositos";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Mis Depositos
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i>  <a href="@Url.Action("Index", "Dashboard")">Dashboard</a>
            </li>
            <li>
                <i class="fa fa-money"></i>  <a href="@Url.Action("ListarCuentas", "CuentaCorriente")">Mis Cuentas</a>
            </li>
            <li class="active">
                <i class="fa fa-bank"></i> Mis Depositos
            </li>
        </ol>
    </div>
</div>

@if (TempData["Mensaje"] != null)
{
    String Mensaje = TempData["Mensaje"].ToString();

    if (Mensaje.Contains("exitosamente"))
    {
        <div class="alert alert-success fade in" id="mensaje">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>@Mensaje
        </div>
    }
    else
    {
        <div class="alert alert-danger" id="mensaje">
            @Mensaje
        </div>
    }
}

<div class="panel panel-default">
    <div class="panel-heading text main-text">
        <div class="panel-heading">
            <div class="row">
                <div class="col-xs-6">
                    <div>Mis Depositos</div>
                </div>
                <div class="col-xs-6 text-right">
                    <div>@Model.LstDepositos.Count</div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-12">
                <a href="@Url.Action("Edit", "Deposito", new { CuentaId = Model.CuentaId })" class="btn btn-primary square-btn-adjust"><i class="fa fa-plus"></i> Nuevo Deposito</a>
                <br />
                <br />
            </div>
        </div>


        @for (int i = 0; i < Model.LstDepositos.Count(); i++)
        {
            <div class="row">
                <div class="col-md-4">
                    <div class="table-responsive">
                        <div class="col-md-12">
                            <div class="@(Model.EstaPenalizado(i) ? "panel panel-red" : "panel panel-green")">
                                <div class="panel-heading">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div>Del @(Model.obtenerDeposito(i).FechaDeposito.ToShortDateString())</div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="pull-right">Al @(Model.obtenerDeposito(i).FechaVencimiento.Value.ToShortDateString())</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="panel-body">
                                    <div class="col-md-12">
                                        <div id=@("progreso" + i)> </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="table-responsive">
                        <div class="col-md-12">
                            <div class="@(Model.EstaPenalizado(i) ? "panel panel-red" : "panel panel-green")">
                                <div class="panel-heading">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div>Deposito de @(String.Format("{0:C}", Model.obtenerDeposito(i).MontoDepositado))</div>
                                        </div>
                                        <div class="col-md-6 text-right">
                                            <div>@(Model.EstaPenalizado(i) ? "Faltan " + @Model.ObtenerDiasFaltantes(i) + " Día(s)" : "Puede retirar su dinero")</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="panel-body">
                                    <table class="table">
                                        <tr>
                                            <td class="text-muted">Dinero actualmente en la cuenta:</td>
                                            <td class="huge">@(String.Format("{0:C}", Model.AplicarTEAHoy(i, false)))</td>
                                        </tr>
                                        <tr>
                                            <td class="text-muted">Interes ganado si se retira el dia de hoy:</td>
                                            <td class="huge">@String.Format("{0:C}", Model.DineroGanadoHoy(i, Model.EstaPenalizado(i)))</td>
                                        </tr>
                                        <tr>
                                            <td class="text-muted">Dinero total a retirar al fin del periodo:</td>
                                            <td class="huge">@(String.Format("{0:C}", Model.DineroGanadoPeriodo(i, false) + Model.obtenerDeposito(i).MontoDepositado)) </td>
                                        </tr>

                                        <tr>
                                            <td class="text-muted">Interes al fin del periodo:</td>
                                            <td class="huge @(Model.EstaPenalizado(i) ? "text-warning" : "text-success")">@(String.Format("{0:C}", Model.DineroGanadoPeriodo(i, false))) </td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="table-responsive">
                <div class="row">

                    <div class="col-md-6">
                        <a href="@Url.Action("Edit", "Deposito", new { CuentaId = Model.CuentaId, DepositoId = Model.obtenerDeposito(i).DepositoId})" class="btn btn-warning square-btn-adjust"><i class="fa fa-edit"></i> Editar Deposito</a>
                    </div>
                    <div class="col-md-6">
                        <a href="@Url.Action("Eliminar", "Deposito", new { DepositoId = Model.obtenerDeposito(i).DepositoId})" class="btn btn-danger square-btn-adjust pull-right"><i class="fa fa-trash"></i> Eliminar Deposito</a>
                    </div>
                </div>
            </div>
            <br /><br />
        }
        <div class="col-md-12">
            <div class="table-responsive">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-md-12">
                                <div>Reporte:</div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-12">
                                <table class="table">
                                    <tr>
                                        <td>
                                            Total al liquidar todas las cuentas hoy (incl. ITF):
                                        </td>
                                        <td class="huge">
                                            @String.Format("{0:C}", Model.ObtenerTotalDeIngresosAlRetirarHoy())
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Total al liquidar todas las cuentas finalizando los periodos (incl. ITF):
                                        </td>
                                        <td class="huge">
                                            @String.Format("{0:C}", Model.ObtenerTotalDeIngresosPeriodo())
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>














<script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="http://code.jquery.com/jquery-1.8.2.min.js"></script>
<script src="http://cdn.oesmith.co.uk/morris-0.4.1.min.js"></script>
<meta charset=utf-8 />
@for (int i = 0; i < Model.LstDepositos.Count; i++)
{
    <script>
        $(window).resize(function() {
            location.reload();
        });
        $(function() {
            Morris.Donut({
                element: '@("progreso" + i)',
                @if (Model.ObtenerDiasTranscurridos(i) > 0) {
                    @:data: [
                    @:  { label: "Dias por transcurrir", value: @Model.ObtenerDiasFaltantes(i) },
                    @:  { label: "Dias transcurridos", value: @Model.ObtenerDiasTranscurridos(i) }
                    @:],
                }
                else {
                    @:data: [
                    @:  { label: "Dias por transcurrir", value: @Model.ObtenerDiasFaltantes(i) }
                    @:],
                }
                colors: ["#ecf0f1","#2ecc71"],
                resize: true
            });
        });
    </script>
}